### ISSUE TITLE
RNN Character Model - 2 Layer : Throws errors

### ISSUE THREAD

**Issue by mdda** [ebenolson/pydata2015#1]
I'm currently putting together my own presentation for FOSSASIA, which includes a number of your notebooks (with credit).  All of them have been working flawlessly, apart from this one.

When I run through this example, with git versions of theano and lasagne, I get the following 'bad dimensions' error on the "loss_train, norm, hid, hid2 = f_train(x, y, hid, hid2)" line (I changed the BATCHSIZE to 64, just for more clues) : 

`
ValueError: Shape mismatch: x has 1 cols (and 64 rows) but y has 64 rows (and 200 cols)
Apply node that caused the error: Dot22(Alloc.0, <TensorType(float32, matrix)>)
Toposort index: 60
Inputs types: [TensorType(float32, col), TensorType(float32, matrix)]
Inputs shapes: [(64, 1), (64, 200)]
Inputs strides: [(4, 4), (800, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[InplaceDimShuffle{x,0,1}(Dot22.0)]]
`

Neither training nor test phases work.  The saved network weights still load fine.

I guess that some changes to GRUs, etc, were made since you did this PyCon - though I don't think that the learn_init default change could be the problem.  Is there something which leaps out as being the potential source of the problem?

**Comment by ebenolson** [comment]
Thanks for the report. The problem was a change introduced in https://github.com/Lasagne/Lasagne/pull/549 which requires the hidden initialization to the recurrent layers to be wrapped by an `InputLayer`. I've pushed a fix.

**Comment by mdda** [comment]
Many thanks for the quick response.  I've now incorporated this notebook (with a couple of customizations) into the Workshop that I'm doing in Singapore : https://github.com/mdda/fossasia-2016_deep-learning/tree/master/notebooks

FWIW : I had been tempted to use Keras-Tensorflow as the foundation on which to build, but I really wanted to hand out VMs to everyone at the workshop, so that their own laptops (multiplatform) could run everything.  Given the combination of memory requirement and familiarity, Lasagne-Theano won the day easily : Lots of happy attendees.
