### ISSUE TITLE
Unable to load Vgg16.pkl

### ISSUE THREAD

**Issue by rachidasen** [ebenolson/pydata2015#3]
Which os did you used because while loading vgg16.pkl I am getting

`EOFError                                  Traceback (most recent call last)     
<ipython-input-21-db9c81aff126> in <module>()
      1 pkl=open('vgg16.pkl','rb')
      2 # d = pickle.load(o)
----> 3 a=pickle.load(pkl)
EOF Error:`

Me using Linux

**Comment by ebenolson** [comment]
linux. sounds like your file might be corrupt, the md5 should
be 57858ec9bb7435e99c78a0520e6c5d3e
